# From Week 5 videos

In [14]:
# Import NumPy package
import numpy as np

In [6]:
t = [
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 0], [1, 2]],
    [[8, 9], [0, 1], [5, 6]],
]


In [7]:
t[0][0]

[1, 2]

In [8]:
t [0][0][0]

1

In [11]:
x = [
    [1, 2.0],
    [3, 4],
]

In [12]:
y = [
    ["a", "b"],
    ["c", "d"],
]

## Multidimensional Homogenous Arrays

In [17]:
# A 2D array of integers
n = np.array([[1, 2, 3], [4, 5, 6]])

# Show array
print(n)

[[1 2 3]
 [4 5 6]]


In [18]:
# Number of dimensions
print(n.ndim)

2


In [20]:
# Shape of the array
print(n.shape)

(2, 3)


In [21]:
# Type of the elements.
print(n.dtype)

int64


## Operations

In [28]:
# Two Arrays.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9,0], [4,7], [5,6]])

# Show
print('A:')
print(A)
print('B:')
print(B)

A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]


In [24]:
# Adding constants.
A + 5

array([[6, 7],
       [8, 9]])

In [25]:
# Adding 2 arrays
A + B

array([[ 6,  8],
       [10, 12]])

In [29]:
# Adding 2 arrays of different dimensions.
A + C

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [27]:
# Multiplying by  constant.
A * 5

array([[ 5, 10],
       [15, 20]])

In [ ]:
# Multiplying two arrays.
A * B

array([[ 5, 12],
       [21, 32]])

In [32]:
# Matrix multiplication
A @ B

array([[19, 22],
       [43, 50]])

## Accessing Elements

In [42]:
P = np.array([[1, 2], [3, 4]])

In [43]:
P

array([[1, 2],
       [3, 4]])

In [ ]:
# Bring back the second item in row 1
# 0 will return the first row, where as the 1 brings back the second item in row 2
P[0][1]

np.int64(2)

In [46]:
# grab first column
P[:, 0]

array([1, 3])

In [47]:
# Recall P
P

array([[1, 2],
       [3, 4]])

In [48]:
# Zeroth row, first column.
P [0,1]

np.int64(2)

In [49]:
# First Row
P [0]

array([1, 2])

In [51]:
# First column
P[:,1]

array([2, 4])

In [57]:
# An array with lots of elements
U = np.arange(10, 21, 3)

# Show U
print(U)

[10 13 16 19]


In [62]:
# An array with lots of elements
U = np.arange(20)

# Show U
print(U)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [63]:
# The first five elements.
U[:5]

array([0, 1, 2, 3, 4])

In [64]:
# The next five elements.
U[5:10]

array([5, 6, 7, 8, 9])

In [66]:
# The elements from index 5 up
U[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [67]:
# Every second element
U[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# Every second element (alternative way)
U[0:len(U):2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# End